version: 0.53

# Actions, the classes that implement them, and where they should appear
# in the action menu
actions:
  blame:
    class: SVN::Web::Blame
    action_menu:
      show:
        - file
      link_text: (view blame)
  browse:
    class: SVN::Web::Browse
    action_menu:
      show:
        - directory
      link_text: (browse directory)
  checkout:
    class: SVN::Web::Checkout
    action_menu:
      show:
        - file
      link_text: (checkout)
  diff:
    class: SVN::Web::Diff
  list:
    class: SVN::Web::List
  log:
    class: SVN::Web::Log
    action_menu:
      show:
        - file
        - directory
      link_text: (view revision log)
  revision:
    class: SVN::Web::Revision
    opts:
      max_diff_size: 1000000
      show_diff: 1
  rss:
    class: SVN::Web::RSS
    action_menu:
      show:
        - file
        - directory
      link_text: (rss)
      head_only: 1
      icon: /css/trac/feed-icon-16x16.png
  view:
    class: SVN::Web::View
    action_menu:
      show:
        - file
      link_text: (view file)

# Languages.  Specify the localisation files, and how they should be described
# in the web interface.  You probably don't want to change this.
languages:
  en: English
  fr: Fran&ccedil;ais
  zh_cn: Chinese (Simplified)
  zh_tw: Chinese (Traditional)

# Set the default language here.  If not set, English is used
#default_language: fr

# Time and date formatting
timedate_format: '%Y/%m/%d %H:%M:%S'

# Timezone.  Uncomment the next line to use the server's timezone instead
# of UTC.  Or, specify a literal timezone (C<timezone: 'EST'> for example)
#timezone: local

# set your repository path below:
#
#repos:
#  test: '/tmp/svnweb-test'
#  test2: '/tmp/svnweb-test2'
repos:
   openwebmail: '/home/alex/openwebmail.acatysmoof.com/dev/svn'
   openwebmail_website: '/home/alex/openwebmail.acatysmoof.com/dev/svn'
#
# or a parent path contains repositories
#
#reposparent: '/path/to/repositories'
#
# if you set a parent you can block specific repositories
# like this:
#
#block:
#  - 'blocked1'
#  - 'blocked2'
#

templatedirs:
  - 'template/owm'

style: '/dev/svnweb/css/owm/svnweb.css'



